### Flask app with HAProxy load balancing ###
---
- name: Configure and deploy Flask app with HAProxy load balancing
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

- name: Configure web servers
  hosts: webservers
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name: ['python3', 'python3-pip', 'python3-flask']
        state: present

    - name: Create directory for Flask app
      file:
        path: /opt/flaskapp
        state: directory
        mode: '0755'

    - name: Copy Flask application
      copy:
        content: |
          import flask
          import time
          import socket

          h_name = socket.gethostname()
          IP_addres = socket.gethostbyname(h_name)

          app = flask.Flask(__name__)

          @app.route('/')
          def index():
              Time= time.strftime("%H:%M:%S")
              return Time+" Serving from "+h_name+" ("+IP_addres+")\n"

          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=5000)
        dest: /opt/flaskapp/application2.py
        mode: '0644'

    - name: Install Flask
      pip:
        name: flask
        executable: pip3

    - name: Create systemd service for Flask app
      copy:
        content: |
          [Unit]
          Description=Flask Application
          After=network.target

          [Service]
          User=root
          WorkingDirectory=/opt/flaskapp
          ExecStart=/usr/bin/python3 /opt/flaskapp/application2.py
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/flaskapp.service
        mode: '0644'

    - name: Enable and start Flask service
      systemd:
        name: flaskapp
        enabled: yes
        state: started
        daemon_reload: yes

- name: Configure HAProxy
  hosts: HAproxy
  become: yes

  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify: Restart HAProxy

    - name: Enable HAProxy to start on boot
      service:
        name: haproxy
        enabled: yes

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
