---
- name: Setup HAproxy
  hosts: HAproxy
  become: true
  tasks:
    - name: Install HAproxy
      apt:
        name: haproxy
        state: present
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Configure HAproxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAproxy

    - name: Enable and Start HAproxy
      service:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: Restart HAproxy
      service:
        name: haproxy
        state: restarted

- name: Setup Flask Application
  hosts: webservers
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-flask
        update_cache: true

    - name: Deploy Flask app
      git:
        repo: 'https://github.com/patrikarlos/NSO_A2.git'
        dest: /home/ubuntu/flaskapp

    - name: Install Flask
      pip:
        name: flask

    - name: Run Flask app
      shell: |
        nohup python3 /home/ubuntu/flaskapp/application2.py > /home/ubuntu/flaskapp/app.log 2>&1 &
      args:
        executable: /bin/bash

- name: Test the application
  hosts: localhost
  tasks:
    - name: Test flask responses
      uri:
        url: "http://89.46.83.95"
        return_content: yes
      register: result

    - debug:
        var: result.content
    
    - name: Verify all webservers responded
      fail:
        msg: "Not all webservers responded during test."
      when: "'devA' not in result.result[0].content and 'devB' not in result.result[1].content and 'devC' not in result.result[2].content"
